### ISSUE TITLE
Target input catalogue definition and discussion

### ISSUE THREAD

**Issue by rubyvanrooyen** [rubyvanrooyen/astrokat#4]
Wiki describing the input target used in the catalogue files for information
https://github.com/rubyvanrooyen/astrokat/wiki/Observation-target-specification

Please review and add/correct information

- Not sure how to describe the flux model and if it is necessary on the user level, since the calibrator catalogues are under katconfig control

- Do we still use the `delaycal` tag?

**Comment by mserylak** [comment]
Wiki reviewed. Minor corrections.

- I believe we should expose users to as much information as possible to avoid . I would just put in explanation from katpoint.Target or referred user to the definition.
- `delaycal` tag is in use ATM.

**Comment by spassmoor** [comment]
The Target Name Should be autogenerated if it is left blank. 
The use of '|' and '*'  in target name is overkill and will complicated processing down the line. there should be only one specified target name. 

> Do we still use the delaycal tag?

Yes this is a valid intent for the backend system so should be supported.

Note satellite targets are specified by TLE (Two line element ) descriptions and just break everything. **_Don't do satellites._**

Need to remove 'tags': ['radec']  from the page https://github.com/rubyvanrooyen/astrokat/wiki/Observation-target-specification

**Comment by rubyvanrooyen** [comment]
Target name convention is in katpoint. Since people are already used to this, should be allowed.
It does not require any work from the observation script, Werner from CAM has already fixed a lot of issues and is on top of it

Updates to implementation
- I removed the stubs of TLE implementation. No current plans to add the capability.
- Removed the redundant 'radec' string in tags when generating the config
- If a target name is not specified when read from catalogue, a dummy name is generated and inserted in the configuration file

I am retiring this issue, the remaining calibrator discussion I am going to add to #5 
This issue discuss the initial full calibrator catalogue work that I am currently working on with CAM
