### ISSUE TITLE
creating a schedule block

### ISSUE THREAD

**Issue by rubyvanrooyen** [rubyvanrooyen/astrokat#6]
Manual instructions

```
configure_obs()
obs.sb.new(owner='Observer')
obs.sb.type=katuilib.ScheduleBlockTypes.OBSERVATION
obs.sb.antenna_spec='available'
obs.sb.controlled_resources_spec='cbf,sdp'
obs.sb.desired_start_time='2018-09-14 10:05:09.406Z'
obs.sb.expected_duration_seconds='60'
obs.sb.description="Test new observation script"
obs.sb.instruction_set="run-obs-script /home/kat/usersnfs/ruby/astrokat/scripts/observe.py -o ruby --profile /home/kat/usersnfs/ruby/astrokat/test/test_targets.yaml --proposal-description='A test' "
obs.sb.to_defined()
obs.sb.to_approved()
obs.sb.unload()
```

Need to update and construct a script that will auto gen

**Comment by ajoubertza** [comment]
@rubyvanrooyen Not sure what you mean by script that will auto gen, but maybe some of the work @wbode-za did recently can be of use?  Script that creates program blocks and schedule blocks from template files:  
- https://github.com/ska-sa/katscripts/blob/master/cam/populate-project-pbs-sbs.py
- https://github.com/ska-sa/katscripts/blob/master/cam/populate-project-pbs-sbs.py

**Comment by rubyvanrooyen** [comment]
@ajoubertza no, sorry , this was a comment to build a dumb temp script to help me test a little more efficiently.
I am almost at the point of showing you how this work, and will hopefully regroup with @wbode-za next week to see what CAM has and how we can unify again.

**Comment by rubyvanrooyen** [comment]
Why does the observation script have to be executable?

Dry-run does not take sb duration into account -- need more discussion
Do I need to add a max duration parameter? Would really like time control to be from CAM only

**Comment by ajoubertza** [comment]
I'm wondering about max duration for PTUSE work as well.  Some scripts have a fixed chunk of work (e.g. visit N targets for M minutes each).   Other just want to run as long as possible, and keep looping through their sources.  Think it would help if we at least include a place to define max duration in the astrokat config.  Maybe we allow an empty value, or -1 to indicate no  limit.

**Comment by rubyvanrooyen** [comment]
Schedule block discussion moved to https://github.com/ska-sa/astrokat/issues/28 and 
https://github.com/ska-sa/astrokat/issues/20
